# evaluacion4_simple_final.py
import flet as ft
import bcrypt
import requests
import oracledb
import os
from datetime import datetime, timedelta

# ============================================================================
# CLASES (igual que tu código original)
# ============================================================================

class Database:
    def __init__(self):
        self.username = os.getenv("ORACLE_USER", "system")
        self.password = os.getenv("ORACLE_PASSWORD", "oracle")
        self.dsn = os.getenv("ORACLE_DSN", "localhost:1521/xe")
        
    def get_connection(self):
        try:
            return oracledb.connect(
                user=self.username,
                password=self.password,
                dsn=self.dsn
            )
        except:
            return None
    
    def init_tables(self):
        conn = self.get_connection()
        if not conn:
            return False
        try:
            cursor = conn.cursor()
            cursor.execute("""
                CREATE TABLE usuarios (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username VARCHAR2(32) UNIQUE NOT NULL,
                    password VARCHAR2(128) NOT NULL
                )
            """)
            cursor.execute("""
                CREATE TABLE CONSULTAS (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    nombre_indicador VARCHAR2(50),
                    fecha_indicador DATE,
                    valor_indicador NUMBER(15,2),
                    fecha_consulta TIMESTAMP,
                    usuario_consulta VARCHAR2(50)
                )
            """)
            conn.commit()
            return True
        except:
            # Si las tablas ya existen, continuar
            return True
        finally:
            conn.close()
    
    def query(self, sql, params=None):
        try:
            conn = self.get_connection()
            if not conn:
                return []
            cursor = conn.cursor()
            cursor.execute(sql, params or {})
            if sql.strip().upper().startswith("SELECT"):
                return cursor.fetchall()
            conn.commit()
            return True
        except Exception as e:
            print(f"Error: {e}")
            return []

# ============================================================================
# APLICACIÓN FLET SIMPLE
# ============================================================================

def main(page: ft.Page):
    page.title = "Sistema de Indicadores"
    page.window_width = 700
    page.window_height = 550
    
    # Inicializar BD
    db = Database()
    db.init_tables()
    
    usuario_actual = None
    consulta_actual = None
    
    # ========================
    # PANTALLA 1: LOGIN
    # ========================
    def mostrar_login():
        page.clean()
        
        user_field = ft.TextField(label="Usuario", width=250)
        pass_field = ft.TextField(label="Contraseña", password=True, width=250)
        
        def login(e):
            nonlocal usuario_actual
            
            # Consultar usuario en BD
            resultado = db.query(
                "SELECT password FROM usuarios WHERE username = :1",
                [user_field.value]
            )
            
            if resultado:
                hash_almacenado = resultado[0][0]
                # Verificar contraseña con bcrypt
                if bcrypt.checkpw(pass_field.value.encode(), hash_almacenado.encode()):
                    usuario_actual = user_field.value
                    mostrar_principal()
                    return
            
            # Mostrar error
            mensaje = ft.Text("Usuario o contraseña incorrectos")
            page.add(mensaje)
            page.update()
        
        page.add(
            ft.Column([
                ft.Text("INICIAR SESIÓN", size=24),
                ft.Container(height=20),
                user_field,
                pass_field,
                ft.Container(height=20),
                ft.ElevatedButton("Ingresar", on_click=login, width=250),
                ft.TextButton("Registrarse", on_click=lambda e: mostrar_registro())
            ], horizontal_alignment=ft.CrossAxisAlignment.CENTER)
        )
    
    # ========================
    # PANTALLA 2: REGISTRO
    # ========================
    def mostrar_registro():
        page.clean()
        
        user_field = ft.TextField(label="Usuario", width=250)
        pass_field = ft.TextField(label="Contraseña", password=True, width=250)
        pass2_field = ft.TextField(label="Confirmar", password=True, width=250)
        
        def registrar(e):
            # Validaciones
            if len(user_field.value) < 3:
                page.add(ft.Text("Usuario mínimo 3 caracteres"))
                page.update()
                return
            
            if pass_field.value != pass2_field.value:
                page.add(ft.Text("Las contraseñas no coinciden"))
                page.update()
                return
            
            # Crear hash con bcrypt
            hash_password = bcrypt.hashpw(
                pass_field.value.encode(),
                bcrypt.gensalt(12)
            ).decode()
            
            # Insertar en BD
            if db.query(
                "INSERT INTO usuarios (username, password) VALUES (:1, :2)",
                [user_field.value, hash_password]
            ):
                page.add(ft.Text("Usuario creado"))
                page.update()
                mostrar_login()
            else:
                page.add(ft.Text("Error: Usuario ya existe"))
                page.update()
        
        page.add(
            ft.Column([
                ft.Text("REGISTRO", size=24),
                ft.Container(height=20),
                user_field,
                pass_field,
                pass2_field,
                ft.Container(height=20),
                ft.ElevatedButton("Crear Cuenta", on_click=registrar, width=250),
                ft.TextButton("Volver al login", on_click=lambda e: mostrar_login())
            ], horizontal_alignment=ft.CrossAxisAlignment.CENTER)
        )
    
    # ========================
    # PANTALLA 3: PRINCIPAL
    # ========================
    def mostrar_principal():
        page.clean()
        
        def logout(e):
            nonlocal usuario_actual
            usuario_actual = None
            mostrar_login()
        
        page.add(
            ft.Column([
                ft.Row([
                    ft.Text(f"Usuario: {usuario_actual}"),
                    ft.Container(expand=True),
                    ft.ElevatedButton("Salir", on_click=logout)
                ]),
                ft.Text("MENÚ PRINCIPAL", size=20),
                ft.Container(height=30),
                ft.ElevatedButton("Consultar Indicador", 
                                on_click=lambda e: mostrar_consulta(),
                                width=200),
                ft.Container(height=10),
                ft.ElevatedButton("Ver Historial", 
                                on_click=lambda e: mostrar_historial(),
                                width=200)
            ])
        )
    
    # ========================
    # PANTALLA 4: CONSULTA
    # ========================
    def mostrar_consulta():
        page.clean()
        
        # Fecha de ayer (la API tiene datos)
        fecha_valida = (datetime.now() - timedelta(days=1)).strftime("%d-%m-%Y")
        
        # Dropdown
        dropdown = ft.Dropdown(
            label="Indicador",
            width=250,
            options=[
                ft.dropdown.Option("Dólar"),
                ft.dropdown.Option("Euro"),
                ft.dropdown.Option("UF"),
                ft.dropdown.Option("IPC"),
                ft.dropdown.Option("UTM")
            ],
            value="Dólar"
        )
        
        # Campo fecha
        fecha_field = ft.TextField(
            label="Fecha (dd-mm-yyyy)",
            width=250,
            value=fecha_valida
        )
        
        # Resultado
        resultado = ft.Text()
        
        # Botón guardar
        btn_guardar = ft.ElevatedButton("Guardar", disabled=True)
        
        def consultar(e):
            nonlocal consulta_actual
            
            # Mapear indicadores a claves API
            indicadores = {
                "Dólar": "dolar",
                "Euro": "euro",
                "UF": "uf",
                "IPC": "ipc",
                "UTM": "utm"
            }
            
            clave = indicadores.get(dropdown.value)
            fecha = fecha_field.value
            
            # Consultar API mindicador.cl
            try:
                url = f"https://mindicador.cl/api/{clave}/{fecha}"
                response = requests.get(url, timeout=5)
                data = response.json()
                
                if 'serie' in data and len(data['serie']) > 0:
                    valor = data['serie'][0]['valor']
                    resultado.value = f"Valor: {valor}"
                    
                    # Guardar consulta para poder guardar después
                    consulta_actual = {
                        "indicador": dropdown.value,
                        "fecha": fecha,
                        "valor": valor,
                        "fuente": "mindicador.cl"
                    }
                    btn_guardar.disabled = False
                else:
                    resultado.value = "No hay datos"
                    
            except Exception as err:
                resultado.value = f"Error: {str(err)}"
            
            page.update()
        
        def guardar(e):
            nonlocal consulta_actual
            
            if consulta_actual:
                # Obtener próximo ID
                res = db.query("SELECT NVL(MAX(id), 0) + 1 FROM CONSULTAS")
                next_id = res[0][0] if res else 1
                
                # Insertar consulta
                db.query(
                    """
                    INSERT INTO CONSULTAS 
                    (id, nombre_indicador, fecha_indicador, valor_indicador, fecha_consulta, usuario_consulta)
                    VALUES (:1, :2, TO_DATE(:3, 'DD-MM-YYYY'), :4, :5, :6)
                    """,
                    [
                        next_id,
                        consulta_actual["indicador"],
                        consulta_actual["fecha"],
                        consulta_actual["valor"],
                        datetime.now(),
                        usuario_actual
                    ]
                )
                
                resultado.value = "Consulta guardada"
                btn_guardar.disabled = True
                page.update()
        
        btn_guardar.on_click = guardar
        
        page.add(
            ft.Column([
                ft.ElevatedButton("← Volver", on_click=lambda e: mostrar_principal()),
                ft.Text("CONSULTAR INDICADOR", size=20),
                ft.Container(height=20),
                dropdown,
                fecha_field,
                ft.Container(height=10),
                ft.ElevatedButton("Consultar", on_click=consultar, width=250),
                ft.Container(height=20),
                resultado,
                ft.Container(height=10),
                btn_guardar
            ])
        )
    
    # ========================
    # PANTALLA 5: HISTORIAL
    # ========================
    def mostrar_historial():
        page.clean()
        
        # Obtener consultas del usuario
        consultas = db.query(
            "SELECT nombre_indicador, fecha_indicador, valor_indicador, fecha_consulta FROM CONSULTAS WHERE usuario_consulta = :1 ORDER BY fecha_consulta DESC",
            [usuario_actual]
        )
        
        contenido = []
        
        if consultas:
            for nombre, fecha_ind, valor, fecha_cons in consultas:
                fecha_str = fecha_ind.strftime("%d-%m-%Y") if fecha_ind else ""
                hora_str = fecha_cons.strftime("%H:%M") if fecha_cons else ""
                contenido.append(
                    ft.Text(f"{nombre} | {fecha_str} | {valor} | {hora_str}")
                )
        else:
            contenido.append(ft.Text("No hay consultas"))
        
        contenido.append(
            ft.ElevatedButton("← Volver", on_click=lambda e: mostrar_principal())
        )
        
        page.add(
            ft.Column([
                ft.Text("HISTORIAL", size=20),
                ft.Container(height=20),
                *contenido
            ])
        )
    
    # ========================
    # INICIAR
    # ========================
    mostrar_login()

# Ejecutar
ft.app(target=main)